TRUNCATE customer;
INSERT INTO customer(NAME,CONTACT,TELEPHONE,EMAIL,REMARK) VALUES ('ZHANGSAN','ZHANG','122221111','ZHANG@QQ.COM',NULL);
INSERT INTO customer(NAME,CONTACT,TELEPHONE,EMAIL,REMARK) VALUES ('LISI','LIS','122221111','LIS@QQ.COM',NULL);
